import {StyleSheet} from 'react-native';

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

import colors from '../assets/colors';

export default StyleSheet.create({
  card: {
    borderRadius: 6,
    elevation: 3,
    backgroundColor: colors.WHITE,
    shadowOffset: {width: 1, height: 1},
    shadowColor: colors.SHADOW,
    shadowOpacity: 0.3,
    shadowRadius: 2,
    marginHorizontal: 4,
    marginVertical: 6,
    marginBottom: 20,
    width: wp(85),
  },
  flatList: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  cardContent: {
    marginHorizontal: 18,
    marginVertical: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardImage: {
    height: hp(25),
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  viewDetails: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'space-between',
    backgroundColor: colors.LIGHT_GRAY,
    margin: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 6,
    elevation: 2,
    shadowOffset: {width: 1, height: 1},
    shadowColor: colors.DARK_GRAY,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  buttonText: {
    color: colors.LIGHT_GREEN,
    fontSize: wp(4),
    fontWeight: '700',
  },
  header: {
    width: wp('100%'),
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  headerText: {
    fontWeight: 'bold',
    fontSize: wp(20),
    color: colors.SHADOW,
    letterSpacing: 1,
  },
  search: {
    borderRadius: 3,
    borderColor: colors.GRAY,
    padding: 10,
    borderWidth: 1,
    width: wp(60),
    height: hp(6),
    backgroundColor: colors.WHITE,
  },
  cartQty: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    width: 20,
    height: 20,
    backgroundColor: colors.LIGHT_GREEN,
    textAlign: 'center',
    color: colors.WHITE,
    fontSize: 13,
    marginTop: -7,
    marginLeft: -3,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 0,
  },
  modalClose: {
    padding: 5,
    backgroundColor: colors.DARK_GRAY,
    borderRadius: 30,
  },
  modalTitle: {
    marginTop: 20,
    marginLeft: 20,
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.SHADOW,
  },
  addToCartmodalTitle: {
    marginTop: 20,
    fontSize: wp(5),
    textAlign: 'center',
    fontWeight: 'bold',
    color: colors.LIGHT_GREEN,
  },
  payButtons: {
    marginTop: 30,
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
    justifyContent: 'space-between',
  },
  list: {
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 30,
    height: hp(550),
  },
  minicart: {
    flex: 1,
  },
  cartCardContent: {
    marginHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 10,
  },
  cartImageWrapper: {
    justifyContent: 'center',
    padding: 7,
  },
  cartCardImage: {
    height: hp(11),
    width: wp(20),
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
  },
  cartCard: {
    flexDirection: 'row',
  },
  cardActions: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'space-between',
  },
  cartActionButton: {
    backgroundColor: colors.LIGHT_GRAY,
    marginLeft: 10,
    marginRight: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 6,
    elevation: 2,
    shadowOffset: {width: 1, height: 1},
    shadowColor: colors.SHADOW,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  spinnerContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 50,
  },
  loadMoreSpinner: {
    paddingTop: 2,
    height: hp(10),
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    width: '100%',
    paddingHorizontal: 10,
  },
  addproductsModalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'baseline',
    alignSelf: 'flex-end',
    width: '100%',
    paddingHorizontal: 10,
  },
  iconButton: {
    backgroundColor: colors.DARK_GRAY,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  iconButtonEnd: {
    backgroundColor: colors.DARK_GRAY,
    borderRadius: 100,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    padding: 5,
  },
  detailIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  modalBackground: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
  },
  modalContent: {
    width: '80%',
    height: '50%',
    backgroundColor: colors.WHITE,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 7,
  },
  cartModalContent: {
    width: wp(100),
    height: hp(70),
    flex: 1,
    backgroundColor: colors.WHITE,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 7,
  },
  productName: {
    color: colors.MEDIUM_GRAY,
    fontSize: wp(10),
    textAlign: 'center',
    fontWeight: 'bold',
  },
  addToCartproductName: {
    color: colors.MEDIUM_GRAY,
    fontSize: wp(5),
    textAlign: 'center',
    fontWeight: 'bold',
  },
  quantityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: wp('80%'),
    paddingHorizontal: 10,
  },
  productPrice: {
    color: colors.GRAY,
    fontSize: wp(7),
    color: colors.LIGHT_GREEN,
    fontWeight: 'bold',
  },
  modalTitle: {
    color: colors.LIGHT_GREEN,
    fontSize: wp(7),
    fontWeight: 'bold',
  },
  counterContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.DARK_GRAY,
    borderRadius: 5,
  },
  counterColumn: {
    flex: 1,
    borderColor: colors.DARK_GRAY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterInitValueContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initValueStyle: {
    color: colors.DARK_GRAY,
  },
  miniCounterContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.DARK_GRAY,
    borderRadius: 3,
    width: wp(40),
    height: 40,
  },
  miniCartItemPrice: {
    fontSize: 18,
    marginTop: 10,
    marginBottom: 10,
    color: colors.LIGHT_GREEN,
    fontWeight: '700',
  },
  total: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonsContainer: {
    paddingTop: '2%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  totalText: {
    fontSize: wp(6),
    color: colors.SHADOW,
    fontWeight: '700',
  },
  totalPrice: {
    color: colors.LIGHT_GREEN,
  },
  actionButton: {
    flexDirection: 'row',
    backgroundColor: colors.LIGHT_GREEN,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 3,
    elevation: 2,
    shadowOffset: {width: 1, height: 1},
    shadowColor: colors.DARK_GRAY,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  actionButtonOutline: {
    backgroundColor: colors.LIGHT_GRAY,
  },
  payText: {
    color: colors.WHITE,
    fontSize: wp(4),
    fontWeight: '700',
  },
  payTextOutline: {
    color: colors.LIGHT_GREEN,
    fontSize: wp(4),
    fontWeight: '700',
  },
  diabledButton: {
    backgroundColor: colors.GRAY,
    color: colors.DARK_GRAY,
  },
  drawerItemContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingHorizontal: wp(22),
    alignItems: 'center',
    paddingTop: hp(1),
    paddingBottom: wp(5),
  },
  drawerHeaderContainer: {
    flex: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingTop: hp(10),
    paddingBottom: hp(10),
    backgroundColor: colors.LIGHT_GREEN,
    borderBottomRightRadius: 200,
    borderBottomLeftRadius: 200,
    transform: [{scaleX: 1.4}],
    marginBottom: 50,
  },
  drawerItemTitle: {
    marginLeft: 20,
    width: 100,
    fontSize: wp(4),
    fontWeight: 'bold',
    color: colors.DARK_GRAY,
  },
  drawerBottom: {
    height: 70,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  poweredSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  poweredText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.GRAY,
    marginRight: 10,
  },
  oncodeLogo: {
    height: 30,
    width: 80,
  },
  drawerContentContainer: {flex: 2},
  drawerAvatar: {
    width: wp(70),
    height: hp(12),
    transform: [{scaleX: 0.7}],
  },
  infoContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cleanCartWrapper: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  searchShadow: {
    elevation: 1.5,
    shadowOffset: {width: 1, height: 1},
    shadowColor: colors.SHADOW,
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  suggestionList: {
    height: 150,
    borderWidth: 1,
    paddingBottom: 5,
    paddingTop: 5,
    borderColor: colors.GRAY,
    borderTopWidth: 0,
  },
  suggestionListItem: {
    borderColor: colors.LIGHT_GREEN,
    borderWidth: 1,
    borderRadius: 3,
    padding: 5,
    marginVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  suggestionItemText: {
    width: 150,
    color: colors.DARK_GRAY,
    fontWeight: 'bold',
  },
});
