const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const ALL_PRODUCTS_LOADED = 'ALL_PRODUCTS_LOADED';
const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
const AUTH_USER = 'AUTH_USER';
const ADD_TO_CART = 'ADD_TO_CART';
const INCREMENT_PRICE = 'INCREMENT_PRICE';
const EMPTY_CART = 'EMPTY_CART';
const CLEAR_CART = 'CLEAR_CART';
const CREATE_ORDER = 'CREATE_ORDER';
const ORDER_SUCCESS = 'ORDER_SUCCESS';
const ORDER_FAILED = 'ORDER_FAILED';
const GET_ORDERS = 'GET_ORDERS';
const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';
const LOGOUT = 'LOGOUT';
const AUTH_DISCONNECT = 'AUTH_DISCONNECT';
const DELETE_ELEMENT = 'DELETE_ELEMENT';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const EDIT_ELEMENT = 'EDIT_ELEMENT';
const UPDATE_ELEMENT_FROM_LIST = 'UPDATE_ELEMENT_FROM_LIST';
const MODIFY_PRODUCT = 'MODIFY_PRODUCT';
const REHYDRATE = 'persist/REHYDRATE';
const CLEAR_ORDER = 'CLEAR_ORDER';
const FINISH_ORDER = 'FINISH_ORDER';
const ON_UPDATE_ACCOUNT = 'ON_UPDATE_ACCOUNT';
const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
const UPDATING = 'UPDATING';
export {
  UPDATING,
  ON_UPDATE_ACCOUNT,
  UPDATE_ACCOUNT_SUCCESS,
  FINISH_ORDER,
  CLEAR_ORDER,
  REHYDRATE,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_FAILED,
  FETCH_PRODUCTS,
  ALL_PRODUCTS_LOADED,
  AUTH_USER_SUCCESS,
  AUTH_USER_FAILED,
  AUTH_USER,
  INCREMENT_PRICE,
  EMPTY_CART,
  CLEAR_CART,
  ADD_TO_CART,
  CREATE_ORDER,
  ORDER_SUCCESS,
  ORDER_FAILED,
  GET_ORDERS,
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAILED,
  LOGOUT,
  AUTH_DISCONNECT,
  REMOVE_FROM_CART,
  DELETE_ELEMENT,
  EDIT_ELEMENT,
  UPDATE_ELEMENT_FROM_LIST,
  MODIFY_PRODUCT,
};
